### ISSUE TITLE
Problems with domain?

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [webgefrickel/webgefrickel.de#1]
Hi Steffen,

I was reading your amazing posts on mutt when suddenly I got redirected to some crappy ad page. Your domain was stolen? Hope you can get it back!

**Comment by webgefrickel** [comment]
Oops, sorry—me and the guys I share a coworking-space with are doing this every year: some stupidly presentated funky videos as an advent calendar for some customers and friends. This is intended and just a forward to their domain, because I am lazy.

If you still want to access the articles, for now just have a look at them here on github:
https://github.com/webgefrickel/webgefrickel.de/blob/master/public/content/3-blog/20-a-modern-mutt-setup/article.en.md
https://github.com/webgefrickel/webgefrickel.de/blob/master/public/content/3-blog/21-a-modern-mutt-setup-part-two/article.en.md

**Comment by dmitriy-serdyuk** [comment]
Ah! I see
